server:
  build: .
  dockerfile: ./Dockerfile
  working_dir: /app/employee
  volumes:
    - .:/app/employee
  links:
   - db
     #volumes:
     #-   /Users/viveksoundrapandi/Desktop/2019/kumsy/employee_CRUD/employee/employee_mgmt:/app/employee
  ports:
      - "5000:5000"
  environment:
    PYTHONPATH: $PYTHONPATH:/app/employee/t
  command: python manage.py runserver 0.0.0.0:5000
db:
  image: postgres:9.4
  restart: always
